# Generated by Django 2.2.5 on 2019-09-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beingActivated', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('privilege_granted', models.BooleanField()),
                ('pathToImage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.IntegerField()),
                ('entered_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('flag', models.BooleanField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Student')),
            ],
        ),
    ]
