# Generated by Django 2.2.5 on 2019-09-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MorningMode',
        ),
    ]
