# Generated by Django 2.2.5 on 2019-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_school',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
