# Generated by Django 2.2.5 on 2019-09-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_morningmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='morning_mode',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
