# Generated by Django 2.2.5 on 2019-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='movement',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
