# Generated by Django 2.2.5 on 2019-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190920_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_states',
            field=models.ManyToManyField(blank=True, to='api.StudentDateInOutStatus'),
        ),
    ]
